// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactPageDocumentDataSlicesSlice = never;

/**
 * Content for Contact Page documents
 */
interface ContactPageDocumentData {
  /**
   * Slice Zone field in *Contact Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactPageDocumentData>,
    "contact_page",
    Lang
  >;

/**
 * Content for Globals documents
 */
interface GlobalsDocumentData {
  /**
   * Site Logo field in *Globals*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Site Title field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField /**
   * Address field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.address
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  address: prismic.KeyTextField;

  /**
   * Email field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.email
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.phone
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Fax Number field in *Globals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globals.fax_number
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fax_number: prismic.KeyTextField;
}

/**
 * Globals document from Prismic
 *
 * - **API ID**: `globals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalsDocumentData>,
    "globals",
    Lang
  >;

type MenusDocumentDataSlicesSlice = SingleLinkSlice | MenuPanelSlice;

/**
 * Item in *Menus → Partner Links*
 */
export interface MenusDocumentDataPartnerLinksItem {
  /**
   * Link field in *Menus → Partner Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.partner_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *Menus → Partner Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.partner_links[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type MenusDocumentDataSlices1Slice = MultiLinkColumnSlice;

/**
 * Content for Menus documents
 */
interface MenusDocumentData {
  /**
   * Slice Zone field in *Menus*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.slices[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MenusDocumentDataSlicesSlice> /**
   * Policy Link field in *Menus*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.policy_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  policy_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Partner Links field in *Menus*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.partner_links[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  partner_links: prismic.GroupField<
    Simplify<MenusDocumentDataPartnerLinksItem>
  >;

  /**
   * Slice Zone field in *Menus*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.slices1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<MenusDocumentDataSlices1Slice> /**
   * Banner Text field in *Menus*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.banner_text
   * - **Tab**: Announcement
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  banner_text: prismic.RichTextField;
}

/**
 * Menus document from Prismic
 *
 * - **API ID**: `menus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenusDocumentData>, "menus", Lang>;

/**
 * Item in *Offerings Category → Keywords*
 */
export interface OfferingsCategoryDocumentDataKeywordsItem {
  /**
   * Keyword field in *Offerings Category → Keywords*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offerings_category.keywords[].keyword
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keyword: prismic.KeyTextField;
}

/**
 * Content for Offerings Category documents
 */
interface OfferingsCategoryDocumentData {
  /**
   * Icon field in *Offerings Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offerings_category.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Name field in *Offerings Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offerings_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Body field in *Offerings Category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offerings_category.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField /**
   * Title field in *Offerings Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offerings_category.title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  title: prismic.KeyTextField;

  /**
   * Description field in *Offerings Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offerings_category.description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Keywords field in *Offerings Category*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: offerings_category.keywords[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  keywords: prismic.GroupField<
    Simplify<OfferingsCategoryDocumentDataKeywordsItem>
  >;
}

/**
 * Offerings Category document from Prismic
 *
 * - **API ID**: `offerings_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OfferingsCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OfferingsCategoryDocumentData>,
    "offerings_category",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TabbedCarouselSlice
  | AccordionSlice
  | LogoListSlice
  | RichTextSlice
  | ImageTextSlice
  | CallToActionSlice
  | TestimonialsSlice
  | SimpleTextSlice
  | TileGridSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Background Color field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: page.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Partners → Logos*
 */
export interface PartnersDocumentDataLogosItem {
  /**
   * Logo Image field in *Partners → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.logos[].logo_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_image: prismic.ImageField<never>;

  /**
   * Logo Link field in *Partners → Logos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.logos[].logo_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Partners documents
 */
interface PartnersDocumentData {
  /**
   * Title field in *Partners*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Partners*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Partners*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * CTA text field in *Partners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.cta_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * Logos field in *Partners*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.logos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<Simplify<PartnersDocumentDataLogosItem>>;
}

/**
 * Partners document from Prismic
 *
 * - **API ID**: `partners`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PartnersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PartnersDocumentData>,
    "partners",
    Lang
  >;

/**
 * Item in *Resource Category → Keywords*
 */
export interface ResourceCategoryDocumentDataKeywordsItem {
  /**
   * Keyword field in *Resource Category → Keywords*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_category.keywords[].keyword
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keyword: prismic.KeyTextField;
}

/**
 * Content for Resource Category documents
 */
interface ResourceCategoryDocumentData {
  /**
   * Icon field in *Resource Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_category.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Name field in *Resource Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Body field in *Resource Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_category.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField /**
   * Title field in *Resource Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_category.title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  title: prismic.KeyTextField;

  /**
   * Description field in *Resource Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_category.description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Keywords field in *Resource Category*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_category.keywords[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  keywords: prismic.GroupField<
    Simplify<ResourceCategoryDocumentDataKeywordsItem>
  >;
}

/**
 * Resource Category document from Prismic
 *
 * - **API ID**: `resource_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResourceCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResourceCategoryDocumentData>,
    "resource_category",
    Lang
  >;

type ResourcePageDocumentDataSlicesSlice = never;

/**
 * Content for Resource Page documents
 */
interface ResourcePageDocumentData {
  /**
   * Slice Zone field in *Resource Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ResourcePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Resource Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: resource_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Resource Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: resource_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Resource Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Resource Page document from Prismic
 *
 * - **API ID**: `resource_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResourcePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResourcePageDocumentData>,
    "resource_page",
    Lang
  >;

type TeamMembersDocumentDataSlicesSlice = never;

type TeamMembersDocumentDataSlices2Slice = TeamListSlice;

/**
 * Content for Team Members documents
 */
interface TeamMembersDocumentData {
  /**
   * Background Color field in *Team Members*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: team_members.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Title field in *Team Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Team Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Team Members*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Slice Zone field in *Team Members*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeamMembersDocumentDataSlicesSlice> /**
   * Meta Title field in *Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: team_members.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: team_members.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *Team Members*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.slices2[]
   * - **Tab**: Team Members
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<TeamMembersDocumentDataSlices2Slice>;
}

/**
 * Team Members document from Prismic
 *
 * - **API ID**: `team_members`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamMembersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeamMembersDocumentData>,
    "team_members",
    Lang
  >;

export type AllDocumentTypes =
  | ContactPageDocument
  | GlobalsDocument
  | MenusDocument
  | OfferingsCategoryDocument
  | PageDocument
  | PartnersDocument
  | ResourceCategoryDocument
  | ResourcePageDocument
  | TeamMembersDocument;

/**
 * Item in *Accordion → Default → Primary → Accordion Group*
 */
export interface AccordionSliceDefaultPrimaryAccordionGroupItem {
  /**
   * Accordion Title field in *Accordion → Default → Primary → Accordion Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.accordion_group[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Accordion Body field in *Accordion → Default → Primary → Accordion Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.accordion_group[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Accordion Button field in *Accordion → Default → Primary → Accordion Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.accordion_group[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *Accordion → Default → Primary*
 */
export interface AccordionSliceDefaultPrimary {
  /**
   * Background Color field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: accordion.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Title field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Accordion Group field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.accordion_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  accordion_group: prismic.GroupField<
    Simplify<AccordionSliceDefaultPrimaryAccordionGroupItem>
  >;
}

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault;

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Accordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSlice = prismic.SharedSlice<
  "accordion",
  AccordionSliceVariation
>;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Background Color field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: call_to_action.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Text Alignment field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: call_to_action.default.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  text_alignment: prismic.BooleanField;

  /**
   * Title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Item in *ContentCarousel → Default → Primary → Content Card*
 */
export interface ContentCarouselSliceDefaultPrimaryContentCardItem {
  /**
   * Content field in *ContentCarousel → Default → Primary → Content Card*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.default.primary.content_card[].content
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  content: prismic.ContentRelationshipField<
    "resource_category" | "offerings_category"
  >;
}

/**
 * Primary content in *ContentCarousel → Default → Primary*
 */
export interface ContentCarouselSliceDefaultPrimary {
  /**
   * Title field in *ContentCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: content_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content Card field in *ContentCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.default.primary.content_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content_card: prismic.GroupField<
    Simplify<ContentCarouselSliceDefaultPrimaryContentCardItem>
  >;

  /**
   * All Link field in *ContentCarousel → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_carousel.default.primary.all_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  all_link: prismic.ContentRelationshipField<"page">;
}

/**
 * Default variation for ContentCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentCarousel*
 */
type ContentCarouselSliceVariation = ContentCarouselSliceDefault;

/**
 * ContentCarousel Shared Slice
 *
 * - **API ID**: `content_carousel`
 * - **Description**: ContentCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentCarouselSlice = prismic.SharedSlice<
  "content_carousel",
  ContentCarouselSliceVariation
>;

/**
 * Item in *ImageText → Stats → Primary → Stats*
 */
export interface ImageTextSliceStatsPrimaryStatsItem {
  /**
   * number field in *ImageText → Stats → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * description field in *ImageText → Stats → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.stats[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *ImageText → Default → Primary*
 */
export interface ImageTextSliceDefaultPrimary {
  /**
   * Background Color field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: image_text.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Image Side field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.default.primary.image_side
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_side: prismic.BooleanField;

  /**
   * Title field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageText → Stats → Primary*
 */
export interface ImageTextSliceStatsPrimary {
  /**
   * Background Color field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: image_text.stats.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Image Side field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.stats.primary.image_side
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_side: prismic.BooleanField;

  /**
   * Title field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Image field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Stats field in *ImageText → Stats → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.stats.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<ImageTextSliceStatsPrimaryStatsItem>>;
}

/**
 * Stats variation for ImageText Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceStats = prismic.SharedSliceVariation<
  "stats",
  Simplify<ImageTextSliceStatsPrimary>,
  never
>;

/**
 * Primary content in *ImageText → Video → Primary*
 */
export interface ImageTextSliceVideoPrimary {
  /**
   * Background Color field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: image_text.video.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Image Side field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_text.video.primary.image_side
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_side: prismic.BooleanField;

  /**
   * Title field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Video field in *ImageText → Video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.video.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;
}

/**
 * Video variation for ImageText Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<ImageTextSliceVideoPrimary>,
  never
>;

/**
 * Slice variation for *ImageText*
 */
type ImageTextSliceVariation =
  | ImageTextSliceDefault
  | ImageTextSliceStats
  | ImageTextSliceVideo;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `image_text`
 * - **Description**: ImageText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSlice = prismic.SharedSlice<
  "image_text",
  ImageTextSliceVariation
>;

/**
 * Item in *LogoList → Default → Primary → Logos*
 */
export interface LogoListSliceDefaultPrimaryLogosItem {
  /**
   * Logo Image field in *LogoList → Default → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.default.primary.logos[].logo_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_image: prismic.ImageField<never>;

  /**
   * Logo Link field in *LogoList → Default → Primary → Logos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.default.primary.logos[].logo_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *LogoList → LogoList with Call to Action → Primary → Logos*
 */
export interface LogoListSliceLogoListWithCallToActionPrimaryLogosItem {
  /**
   * Logo Image field in *LogoList → LogoList with Call to Action → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.logos[].logo_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_image: prismic.ImageField<never>;

  /**
   * Logo Link field in *LogoList → LogoList with Call to Action → Primary → Logos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.logos[].logo_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *LogoList → Default → Primary*
 */
export interface LogoListSliceDefaultPrimary {
  /**
   * Background Color field in *LogoList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: logo_list.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Title field in *LogoList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *LogoList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Logos field in *LogoList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<Simplify<LogoListSliceDefaultPrimaryLogosItem>>;

  /**
   * Button field in *LogoList → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Learn More
   * - **API ID Path**: logo_list.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for LogoList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoListSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *LogoList → LogoList with Call to Action → Primary*
 */
export interface LogoListSliceLogoListWithCallToActionPrimary {
  /**
   * Background Color field in *LogoList → LogoList with Call to Action → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Title field in *LogoList → LogoList with Call to Action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *LogoList → LogoList with Call to Action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Logos field in *LogoList → LogoList with Call to Action → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<
    Simplify<LogoListSliceLogoListWithCallToActionPrimaryLogosItem>
  >;

  /**
   * Button field in *LogoList → LogoList with Call to Action → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Learn More
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Call to Action Title field in *LogoList → LogoList with Call to Action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_title: prismic.RichTextField;

  /**
   * Call to Action Body field in *LogoList → LogoList with Call to Action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.cta_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_body: prismic.RichTextField;

  /**
   * Call to Action Button field in *LogoList → LogoList with Call to Action → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.logoListWithCallToAction.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * LogoList with Call to Action variation for LogoList Slice
 *
 * - **API ID**: `logoListWithCallToAction`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSliceLogoListWithCallToAction =
  prismic.SharedSliceVariation<
    "logoListWithCallToAction",
    Simplify<LogoListSliceLogoListWithCallToActionPrimary>,
    never
  >;

/**
 * Slice variation for *LogoList*
 */
type LogoListSliceVariation =
  | LogoListSliceDefault
  | LogoListSliceLogoListWithCallToAction;

/**
 * LogoList Shared Slice
 *
 * - **API ID**: `logo_list`
 * - **Description**: LogoList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoListSlice = prismic.SharedSlice<
  "logo_list",
  LogoListSliceVariation
>;

/**
 * Item in *MenuPanel → Default → Primary → Link Group*
 */
export interface MenuPanelSliceDefaultPrimaryLinkGroupItem {
  /**
   * Title field in *MenuPanel → Default → Primary → Link Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_group[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Link field in *MenuPanel → Default → Primary → Link Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_group[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *MenuPanel → Default → Primary → Link with Paragraph*
 */
export interface MenuPanelSliceDefaultPrimaryLinkWithParagraphItem {
  /**
   * Link Title field in *MenuPanel → Default → Primary → Link with Paragraph*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_with_paragraph[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Body field in *MenuPanel → Default → Primary → Link with Paragraph*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_with_paragraph[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Item in *MenuPanel → MenuPanel - Accordion → Primary → Accordion*
 */
export interface MenuPanelSliceMenuPanelAccordionPrimaryAccordionItem {
  /**
   * Menu Panel Title field in *MenuPanel → MenuPanel - Accordion → Primary → Accordion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.menuPanelAccordion.primary.Accordion[].menu_panel_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_panel_title: prismic.KeyTextField;

  /**
   * Body field in *MenuPanel → MenuPanel - Accordion → Primary → Accordion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.menuPanelAccordion.primary.Accordion[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *MenuPanel → MenuPanel - Accordion → Primary → Accordion*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.menuPanelAccordion.primary.Accordion[].button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Link field in *MenuPanel → MenuPanel - Accordion → Primary → Accordion*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.menuPanelAccordion.primary.Accordion[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *MenuPanel → Default → Primary*
 */
export interface MenuPanelSliceDefaultPrimary {
  /**
   * Menu Display field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.menu_display
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_display: prismic.KeyTextField;

  /**
   * Title field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Columns field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: menu_panel.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  columns: prismic.BooleanField;

  /**
   * Link Group field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link_group: prismic.GroupField<
    Simplify<MenuPanelSliceDefaultPrimaryLinkGroupItem>
  >;

  /**
   * Link with Paragraph field in *MenuPanel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.default.primary.link_with_paragraph[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link_with_paragraph: prismic.GroupField<
    Simplify<MenuPanelSliceDefaultPrimaryLinkWithParagraphItem>
  >;
}

/**
 * Default variation for MenuPanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuPanelSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MenuPanel → MenuPanel - Accordion → Primary*
 */
export interface MenuPanelSliceMenuPanelAccordionPrimary {
  /**
   * Menu_Display field in *MenuPanel → MenuPanel - Accordion → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.menuPanelAccordion.primary.menu_display
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_display: prismic.KeyTextField;

  /**
   * Title field in *MenuPanel → MenuPanel - Accordion → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.menuPanelAccordion.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Accordion field in *MenuPanel → MenuPanel - Accordion → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_panel.menuPanelAccordion.primary.Accordion[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Accordion: prismic.GroupField<
    Simplify<MenuPanelSliceMenuPanelAccordionPrimaryAccordionItem>
  >;
}

/**
 * MenuPanel - Accordion variation for MenuPanel Slice
 *
 * - **API ID**: `menuPanelAccordion`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuPanelSliceMenuPanelAccordion = prismic.SharedSliceVariation<
  "menuPanelAccordion",
  Simplify<MenuPanelSliceMenuPanelAccordionPrimary>,
  never
>;

/**
 * Slice variation for *MenuPanel*
 */
type MenuPanelSliceVariation =
  | MenuPanelSliceDefault
  | MenuPanelSliceMenuPanelAccordion;

/**
 * MenuPanel Shared Slice
 *
 * - **API ID**: `menu_panel`
 * - **Description**: MenuPanel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuPanelSlice = prismic.SharedSlice<
  "menu_panel",
  MenuPanelSliceVariation
>;

/**
 * Primary content in *MultiLinkColumn → Default → Primary*
 */
export interface MultiLinkColumnSliceDefaultPrimary {
  /**
   * Title field in *MultiLinkColumn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_link_column.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Link field in *MultiLinkColumn → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_link_column.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for MultiLinkColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultiLinkColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MultiLinkColumnSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MultiLinkColumn*
 */
type MultiLinkColumnSliceVariation = MultiLinkColumnSliceDefault;

/**
 * MultiLinkColumn Shared Slice
 *
 * - **API ID**: `multi_link_column`
 * - **Description**: MultiLinkColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultiLinkColumnSlice = prismic.SharedSlice<
  "multi_link_column",
  MultiLinkColumnSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Text Alignment field in *RichText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rich_text.default.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  text_alignment: prismic.BooleanField;

  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SimpleText → Default → Primary*
 */
export interface SimpleTextSliceDefaultPrimary {
  /**
   * Background Color field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: simple_text.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Text Alignment field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: simple_text.default.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  text_alignment: prismic.BooleanField;

  /**
   * Tagline field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *SimpleText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for SimpleText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleText*
 */
type SimpleTextSliceVariation = SimpleTextSliceDefault;

/**
 * SimpleText Shared Slice
 *
 * - **API ID**: `simple_text`
 * - **Description**: SimpleText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleTextSlice = prismic.SharedSlice<
  "simple_text",
  SimpleTextSliceVariation
>;

/**
 * Primary content in *SingleLink → Default → Primary*
 */
export interface SingleLinkSliceDefaultPrimary {
  /**
   * Link field in *SingleLink → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: single_link.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for SingleLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SingleLinkSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SingleLink → SingleLink - Button with Icon → Primary*
 */
export interface SingleLinkSliceSingleLinkButtonIconPrimary {
  /**
   * Icon field in *SingleLink → SingleLink - Button with Icon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: single_link.singleLinkButtonIcon.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *SingleLink → SingleLink - Button with Icon → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: single_link.singleLinkButtonIcon.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Icon Only"
  >;
}

/**
 * SingleLink - Button with Icon variation for SingleLink Slice
 *
 * - **API ID**: `singleLinkButtonIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleLinkSliceSingleLinkButtonIcon = prismic.SharedSliceVariation<
  "singleLinkButtonIcon",
  Simplify<SingleLinkSliceSingleLinkButtonIconPrimary>,
  never
>;

/**
 * Slice variation for *SingleLink*
 */
type SingleLinkSliceVariation =
  | SingleLinkSliceDefault
  | SingleLinkSliceSingleLinkButtonIcon;

/**
 * SingleLink Shared Slice
 *
 * - **API ID**: `single_link`
 * - **Description**: SingleLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleLinkSlice = prismic.SharedSlice<
  "single_link",
  SingleLinkSliceVariation
>;

/**
 * Item in *TabbedCarousel → TabbedCarousel → Primary → Tab*
 */
export interface TabbedCarouselSliceDefaultPrimaryTabItem {
  /**
   * Tab Label field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].tab_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tab_label: prismic.KeyTextField;

  /**
   * Card Title field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].card_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_title: prismic.RichTextField;

  /**
   * Card Description field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].card_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_description: prismic.RichTextField;

  /**
   * Card Image field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Card Link field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].card_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Audio Media (Optional) field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].audio_media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  audio_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Audio Media Alt Text (Optional) field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].audio_media_alt_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  audio_media_alt_text: prismic.KeyTextField;

  /**
   * Image Media (Campaign Variant) field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].image_media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_media: prismic.ImageField<never>;

  /**
   * Rich Text (Campaign Variant) field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField;

  /**
   * Card Button field in *TabbedCarousel → TabbedCarousel → Primary → Tab*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Learn More
   * - **API ID Path**: tabbed_carousel.default.primary.tab[].card_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *TabbedCarousel → TabbedCarousel → Primary*
 */
export interface TabbedCarouselSliceDefaultPrimary {
  /**
   * TItle field in *TabbedCarousel → TabbedCarousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *TabbedCarousel → TabbedCarousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Variant field in *TabbedCarousel → TabbedCarousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Short Card
   * - **API ID Path**: tabbed_carousel.default.primary.variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"Short Card" | "Campaign Card", "filled">;

  /**
   * Tab field in *TabbedCarousel → TabbedCarousel → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tabbed_carousel.default.primary.tab[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tab: prismic.GroupField<Simplify<TabbedCarouselSliceDefaultPrimaryTabItem>>;
}

/**
 * TabbedCarousel variation for TabbedCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TabbedCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TabbedCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TabbedCarousel*
 */
type TabbedCarouselSliceVariation = TabbedCarouselSliceDefault;

/**
 * TabbedCarousel Shared Slice
 *
 * - **API ID**: `tabbed_carousel`
 * - **Description**: TabbedCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TabbedCarouselSlice = prismic.SharedSlice<
  "tabbed_carousel",
  TabbedCarouselSliceVariation
>;

/**
 * Item in *TeamList → Default → Primary → Team Member*
 */
export interface TeamListSliceDefaultPrimaryTeamMemberItem {
  /**
   * Image field in *TeamList → Default → Primary → Team Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_member[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TeamList → Default → Primary → Team Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_member[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *TeamList → Default → Primary → Team Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_member[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;
}

/**
 * Primary content in *TeamList → Default → Primary*
 */
export interface TeamListSliceDefaultPrimary {
  /**
   * Background Color field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark">;

  /**
   * Title field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Team Member field in *TeamList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_list.default.primary.team_member[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_member: prismic.GroupField<
    Simplify<TeamListSliceDefaultPrimaryTeamMemberItem>
  >;
}

/**
 * Default variation for TeamList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamList*
 */
type TeamListSliceVariation = TeamListSliceDefault;

/**
 * TeamList Shared Slice
 *
 * - **API ID**: `team_list`
 * - **Description**: TeamList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamListSlice = prismic.SharedSlice<
  "team_list",
  TeamListSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Image field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Quote field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Author field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Author Title field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].author_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_title: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Background Color field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: testimonials.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Image Side field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: testimonials.default.primary.image_side
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_side: prismic.BooleanField;

  /**
   * Image field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Item in *TileGrid → Default → Primary → Tiles*
 */
export interface TileGridSliceDefaultPrimaryTilesItem {
  /**
   * Tile Icon field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.default.primary.tiles[].tile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tile_image: prismic.ImageField<never>;

  /**
   * Tile Title field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.default.primary.tiles[].tile_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tile_title: prismic.RichTextField;

  /**
   * Tile Body field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.default.primary.tiles[].tile_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tile_body: prismic.RichTextField;

  /**
   * Tile Button field in *TileGrid → Default → Primary → Tiles*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.default.primary.tiles[].tile_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tile_button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *TileGrid → IconTile → Primary → Tiles*
 */
export interface TileGridSliceIconTilePrimaryTilesItem {
  /**
   * Tile Icon field in *TileGrid → IconTile → Primary → Tiles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.iconTile.primary.tiles[].tile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tile_image: prismic.ImageField<never>;

  /**
   * Tile Title field in *TileGrid → IconTile → Primary → Tiles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.iconTile.primary.tiles[].tile_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tile_title: prismic.RichTextField;

  /**
   * Tile Button field in *TileGrid → IconTile → Primary → Tiles*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.iconTile.primary.tiles[].tile_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tile_button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *TileGrid → ImageTile → Primary → Tiles*
 */
export interface TileGridSliceImageTilePrimaryTilesItem {
  /**
   * Tile Icon field in *TileGrid → ImageTile → Primary → Tiles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.imageTile.primary.tiles[].tile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tile_image: prismic.ImageField<never>;

  /**
   * Tile Title field in *TileGrid → ImageTile → Primary → Tiles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.imageTile.primary.tiles[].tile_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tile_title: prismic.RichTextField;

  /**
   * Tile Body field in *TileGrid → ImageTile → Primary → Tiles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.imageTile.primary.tiles[].tile_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tile_body: prismic.RichTextField;

  /**
   * Tile Button field in *TileGrid → ImageTile → Primary → Tiles*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.imageTile.primary.tiles[].tile_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tile_button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *TileGrid → Default → Primary*
 */
export interface TileGridSliceDefaultPrimary {
  /**
   * Background Color field in *TileGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: tile_grid.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Columns field in *TileGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 2
   * - **API ID Path**: tile_grid.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  columns: prismic.SelectField<"2" | "3" | "4", "filled">;

  /**
   * Title field in *TileGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *TileGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Tiles field in *TileGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.default.primary.tiles[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tiles: prismic.GroupField<Simplify<TileGridSliceDefaultPrimaryTilesItem>>;

  /**
   * Button field in *TileGrid → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for TileGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TileGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TileGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TileGrid → IconTile → Primary*
 */
export interface TileGridSliceIconTilePrimary {
  /**
   * Background Color field in *TileGrid → IconTile → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: tile_grid.iconTile.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Columns field in *TileGrid → IconTile → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 2
   * - **API ID Path**: tile_grid.iconTile.primary.columns
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  columns: prismic.SelectField<"2" | "3" | "4", "filled">;

  /**
   * Title field in *TileGrid → IconTile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.iconTile.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *TileGrid → IconTile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.iconTile.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Tiles field in *TileGrid → IconTile → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.iconTile.primary.tiles[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tiles: prismic.GroupField<Simplify<TileGridSliceIconTilePrimaryTilesItem>>;

  /**
   * Button field in *TileGrid → IconTile → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.iconTile.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * IconTile variation for TileGrid Slice
 *
 * - **API ID**: `iconTile`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TileGridSliceIconTile = prismic.SharedSliceVariation<
  "iconTile",
  Simplify<TileGridSliceIconTilePrimary>,
  never
>;

/**
 * Primary content in *TileGrid → ImageTile → Primary*
 */
export interface TileGridSliceImageTilePrimary {
  /**
   * Background Color field in *TileGrid → ImageTile → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: tile_grid.imageTile.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<"White" | "Light" | "Dark", "filled">;

  /**
   * Columns field in *TileGrid → ImageTile → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 2
   * - **API ID Path**: tile_grid.imageTile.primary.columns
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  columns: prismic.SelectField<"2" | "3" | "4", "filled">;

  /**
   * Title field in *TileGrid → ImageTile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.imageTile.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *TileGrid → ImageTile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.imageTile.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Tiles field in *TileGrid → ImageTile → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.imageTile.primary.tiles[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tiles: prismic.GroupField<Simplify<TileGridSliceImageTilePrimaryTilesItem>>;

  /**
   * Button field in *TileGrid → ImageTile → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tile_grid.imageTile.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * ImageTile variation for TileGrid Slice
 *
 * - **API ID**: `imageTile`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TileGridSliceImageTile = prismic.SharedSliceVariation<
  "imageTile",
  Simplify<TileGridSliceImageTilePrimary>,
  never
>;

/**
 * Slice variation for *TileGrid*
 */
type TileGridSliceVariation =
  | TileGridSliceDefault
  | TileGridSliceIconTile
  | TileGridSliceImageTile;

/**
 * TileGrid Shared Slice
 *
 * - **API ID**: `tile_grid`
 * - **Description**: TileGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TileGridSlice = prismic.SharedSlice<
  "tile_grid",
  TileGridSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactPageDocument,
      ContactPageDocumentData,
      ContactPageDocumentDataSlicesSlice,
      GlobalsDocument,
      GlobalsDocumentData,
      MenusDocument,
      MenusDocumentData,
      MenusDocumentDataSlicesSlice,
      MenusDocumentDataPartnerLinksItem,
      MenusDocumentDataSlices1Slice,
      OfferingsCategoryDocument,
      OfferingsCategoryDocumentData,
      OfferingsCategoryDocumentDataKeywordsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PartnersDocument,
      PartnersDocumentData,
      PartnersDocumentDataLogosItem,
      ResourceCategoryDocument,
      ResourceCategoryDocumentData,
      ResourceCategoryDocumentDataKeywordsItem,
      ResourcePageDocument,
      ResourcePageDocumentData,
      ResourcePageDocumentDataSlicesSlice,
      TeamMembersDocument,
      TeamMembersDocumentData,
      TeamMembersDocumentDataSlicesSlice,
      TeamMembersDocumentDataSlices2Slice,
      AllDocumentTypes,
      AccordionSlice,
      AccordionSliceDefaultPrimaryAccordionGroupItem,
      AccordionSliceDefaultPrimary,
      AccordionSliceVariation,
      AccordionSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ContentCarouselSlice,
      ContentCarouselSliceDefaultPrimaryContentCardItem,
      ContentCarouselSliceDefaultPrimary,
      ContentCarouselSliceVariation,
      ContentCarouselSliceDefault,
      ImageTextSlice,
      ImageTextSliceDefaultPrimary,
      ImageTextSliceStatsPrimaryStatsItem,
      ImageTextSliceStatsPrimary,
      ImageTextSliceVideoPrimary,
      ImageTextSliceVariation,
      ImageTextSliceDefault,
      ImageTextSliceStats,
      ImageTextSliceVideo,
      LogoListSlice,
      LogoListSliceDefaultPrimaryLogosItem,
      LogoListSliceDefaultPrimary,
      LogoListSliceLogoListWithCallToActionPrimaryLogosItem,
      LogoListSliceLogoListWithCallToActionPrimary,
      LogoListSliceVariation,
      LogoListSliceDefault,
      LogoListSliceLogoListWithCallToAction,
      MenuPanelSlice,
      MenuPanelSliceDefaultPrimaryLinkGroupItem,
      MenuPanelSliceDefaultPrimaryLinkWithParagraphItem,
      MenuPanelSliceDefaultPrimary,
      MenuPanelSliceMenuPanelAccordionPrimaryAccordionItem,
      MenuPanelSliceMenuPanelAccordionPrimary,
      MenuPanelSliceVariation,
      MenuPanelSliceDefault,
      MenuPanelSliceMenuPanelAccordion,
      MultiLinkColumnSlice,
      MultiLinkColumnSliceDefaultPrimary,
      MultiLinkColumnSliceVariation,
      MultiLinkColumnSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SimpleTextSlice,
      SimpleTextSliceDefaultPrimary,
      SimpleTextSliceVariation,
      SimpleTextSliceDefault,
      SingleLinkSlice,
      SingleLinkSliceDefaultPrimary,
      SingleLinkSliceSingleLinkButtonIconPrimary,
      SingleLinkSliceVariation,
      SingleLinkSliceDefault,
      SingleLinkSliceSingleLinkButtonIcon,
      TabbedCarouselSlice,
      TabbedCarouselSliceDefaultPrimaryTabItem,
      TabbedCarouselSliceDefaultPrimary,
      TabbedCarouselSliceVariation,
      TabbedCarouselSliceDefault,
      TeamListSlice,
      TeamListSliceDefaultPrimaryTeamMemberItem,
      TeamListSliceDefaultPrimary,
      TeamListSliceVariation,
      TeamListSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TileGridSlice,
      TileGridSliceDefaultPrimaryTilesItem,
      TileGridSliceDefaultPrimary,
      TileGridSliceIconTilePrimaryTilesItem,
      TileGridSliceIconTilePrimary,
      TileGridSliceImageTilePrimaryTilesItem,
      TileGridSliceImageTilePrimary,
      TileGridSliceVariation,
      TileGridSliceDefault,
      TileGridSliceIconTile,
      TileGridSliceImageTile,
    };
  }
}
