// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  image_text: dynamic(() => import("./ImageText")),
  logo_list: dynamic(() => import("./LogoList")),
  rich_text: dynamic(() => import("./RichText")),
  simple_text: dynamic(() => import("./SimpleText")),
  testimonials: dynamic(() => import("./Testimonials")),
};
