// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  call_to_action: dynamic(() => import("./CallToAction")),
  contact_info: dynamic(() => import("./ContactInfo")),
  content_carousel: dynamic(() => import("./ContentCarousel")),
  content_column: dynamic(() => import("./ContentColumn")),
  content_grid: dynamic(() => import("./ContentGrid")),
  hashtag_banner: dynamic(() => import("./HashtagBanner")),
  image_text: dynamic(() => import("./ImageText")),
  menu_panel: dynamic(() => import("./MenuPanel")),
  multi_link_column: dynamic(() => import("./MultiLinkColumn")),
  rich_text: dynamic(() => import("./RichText")),
  simple_text: dynamic(() => import("./SimpleText")),
  single_link: dynamic(() => import("./SingleLink")),
  tabbed_carousel: dynamic(() => import("./TabbedCarousel")),
  team_list: dynamic(() => import("./TeamList")),
  testimonials: dynamic(() => import("./Testimonials")),
  tile_grid: dynamic(() => import("./TileGrid")),
};
